CREATE TABLE business_table( 
OB_Bus_dataPeriod_startDate DATE NULL, 
OB_Bus_dataPeriod_endDate DATE NULL, 
OB_Bus_dataPeriod_daysCount INT NULL, 
OB_Bus_dataPeriod_fullMonthCount INT NULL, 
OB_Bus_kpi_significantAccountsCount INT NULL, 
OB_Bus_kpi_balance_averageBalanceAmount DECIMAL(20, 2) NULL, 
OB_Bus_kpi_balance_medianBalanceAmount DECIMAL(20, 2) NULL, 
OB_Bus_kpi_balance_minBalanceAmount DECIMAL(20, 2) NULL, 
OB_Bus_kpi_balance_maxBalanceAmount DECIMAL(20, 2) NULL, 
OB_Bus_periodAnalysis_incomeExpensesRatio DECIMAL(20, 2) NULL, 
OB_Bus_periodAnalysis_monthsWithNegativeSavingCount INT NULL, 
OB_Bus_periodAnalysis_expensesAmount_total DECIMAL(20, 2) NULL, 
OB_Bus_periodAnalysis_expensesAmount_average DECIMAL(20, 2) NULL, 
OB_Bus_periodAnalysis_expensesAmount_median DECIMAL(20, 2) NULL, 
OB_Bus_periodAnalysis_incomeAmount_total DECIMAL(20, 2) NULL, 
OB_Bus_periodAnalysis_incomeAmount_average DECIMAL(20, 2) NULL, 
OB_Bus_periodAnalysis_incomeAmount_median DECIMAL(20, 2) NULL, 
OB_Bus_creditScore_score INT NULL, 
OB_Bus_creditScore_tranche INT NULL, 
OB_Bus_creditScore_area TEXT NULL, 
OB_Bus_creditScore_defaultProbability DECIMAL(20, 2) NULL, 
OB_Bus_creditscore_rent_score INT NULL, 
OB_Bus_creditscore_rent_monthlyPotentialInstalmentAmount DECIMAL(20, 2) NULL, 
OB_Bus_risk_gamblingAndGames_gambling_periodTotalTransactionsAmount DECIMAL(20, 2) NULL, 
OB_Bus_risk_gamblingAndGames_gambling_periodTotalTransactionsCount INT NULL, 
OB_Bus_risk_gamblingAndGames_gambling_monthlyAverageTransactionsAmount DECIMAL(20, 2) NULL, 
OB_Bus_risk_gamblingAndGames_gambling_monthlyAverageTransactionsCount INT NULL, 
OB_Bus_risk_gamblingAndGames_gambling_regularity DECIMAL(20, 2) NULL, 
OB_Bus_risk_gamblingAndGames_gambling_expensesRatio DECIMAL(20, 2) NULL, 
OB_Bus_risk_gamblingAndGames_gambling_incomeRatio DECIMAL(20, 2) NULL, 
OB_Bus_risk_unsuccessfulDirectDebit_chargeBack_periodTotalTransactionsAmount DECIMAL(20, 2) NULL, 
OB_Bus_risk_unsuccessfulDirectDebit_chargeBack_periodTotalTransactionsCount INT NULL, 
OB_Bus_risk_unsuccessfulDirectDebit_chargeBack_monthlyAverageTransactionsAmount DECIMAL(20, 2) NULL, 
OB_Bus_risk_unsuccessfulDirectDebit_chargeBack_monthlyAverageTransactionsCount INT NULL, 
OB_Bus_risk_unsuccessfulDirectDebit_fee_periodTotalTransactionsCount INT NULL, 
OB_Bus_risk_unsuccessfulDirectDebit_fee_monthlyAverageTransactionsCount INT NULL, 
OB_Bus_AmtNegUNPAIDEFFECTSL30D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegUNPAIDEFFECTSL60D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegUNPAIDEFFECTSL90D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegUNPAIDEFFECTSL180D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegUNPAIDEFFECTS DECIMAL(20, 2) NULL, 
OB_Bus_NumNegTransUNPAIDEFFECTSL30D INT NULL, 
OB_Bus_NumNegTransUNPAIDEFFECTSL60D INT NULL, 
OB_Bus_NumNegTransUNPAIDEFFECTSL90D INT NULL, 
OB_Bus_NumNegTransUNPAIDEFFECTSL180D INT NULL, 
OB_Bus_NumNegTransUNPAIDEFFECTS INT NULL, 
OB_Bus_HighBalL30D DECIMAL(20, 2) NULL, 
OB_Bus_HighBal31to60D DECIMAL(20, 2) NULL, 
OB_Bus_HighBal61to90D DECIMAL(20, 2) NULL, 
OB_Bus_HighBal91to180D DECIMAL(20, 2) NULL, 
OB_Bus_HighBal181to365D DECIMAL(20, 2) NULL, 
OB_Bus_HighBal366to730D DECIMAL(20, 2) NULL, 
OB_Bus_LowBalL30D DECIMAL(20, 2) NULL, 
OB_Bus_LowBal31to60D DECIMAL(20, 2) NULL, 
OB_Bus_LowBal61to90D DECIMAL(20, 2) NULL, 
OB_Bus_LowBal91to180D DECIMAL(20, 2) NULL, 
OB_Bus_LowBal181to365D DECIMAL(20, 2) NULL, 
OB_Bus_LowBal366to730D DECIMAL(20, 2) NULL, 
OB_Bus_AvgBalL30D DECIMAL(20, 2) NULL, 
OB_Bus_AvgBal31to60D DECIMAL(20, 2) NULL, 
OB_Bus_AvgBal61to90D DECIMAL(20, 2) NULL, 
OB_Bus_AvgBal91to180D DECIMAL(20, 2) NULL, 
OB_Bus_AvgBal181to365D DECIMAL(20, 2) NULL, 
OB_Bus_AvgBal366to730D DECIMAL(20, 2) NULL, 
OB_Bus_TotInflowL30D DECIMAL(20, 2) NULL, 
OB_Bus_TotInflow31to60D DECIMAL(20, 2) NULL, 
OB_Bus_TotInflow61to90D DECIMAL(20, 2) NULL, 
OB_Bus_TotInflow91to180D DECIMAL(20, 2) NULL, 
OB_Bus_TotInflow181to365D DECIMAL(20, 2) NULL, 
OB_Bus_TotInflow366to730D DECIMAL(20, 2) NULL, 
OB_Bus_TotOutflowL30D DECIMAL(20, 2) NULL, 
OB_Bus_TotOutflow31to60D DECIMAL(20, 2) NULL, 
OB_Bus_TotOutflow61to90D DECIMAL(20, 2) NULL, 
OB_Bus_TotOutflow91to180D DECIMAL(20, 2) NULL, 
OB_Bus_TotOutflow181to365D DECIMAL(20, 2) NULL, 
OB_Bus_TotOutflow366to730D DECIMAL(20, 2) NULL, 
Bus_OB_DaysCRL30D INT NULL, 
Bus_OB_DaysCR31to60D INT NULL, 
Bus_OB_DaysCR61to90D INT NULL, 
Bus_OB_DaysCR91to180D INT NULL, 
Bus_OB_DaysCR181to365D INT NULL, 
Bus_OB_DaysCR366to730D INT NULL, 
Bus_OB_DaysDRL30D INT NULL, 
Bus_OB_DaysDR31to60D INT NULL, 
Bus_OB_DaysDR61to90D INT NULL, 
Bus_OB_DaysDR91to180D INT NULL, 
Bus_OB_DaysDR181to365D INT NULL, 
Bus_OB_DaysDR366to730D INT NULL, 
Bus_OB_AvgCRBalL30D DECIMAL(20, 2) NULL, 
Bus_OB_AvgCRBal31to60D DECIMAL(20, 2) NULL, 
Bus_OB_AvgCRBal61to90D DECIMAL(20, 2) NULL, 
Bus_OB_AvgCRBal91to180D DECIMAL(20, 2) NULL, 
Bus_OB_AvgCRBal181to365D DECIMAL(20, 2) NULL, 
Bus_OB_AvgCRBal366to730D DECIMAL(20, 2) NULL, 
Bus_OB_AvgDRBalL30D DECIMAL(20, 2) NULL, 
Bus_OB_AvgDRBal31to60D DECIMAL(20, 2) NULL, 
Bus_OB_AvgDRBal61to90D DECIMAL(20, 2) NULL, 
Bus_OB_AvgDRBal91to180D DECIMAL(20, 2) NULL, 
Bus_OB_AvgDRBal181to365D DECIMAL(20, 2) NULL, 
Bus_OB_AvgDRBal366to730D DECIMAL(20, 2) NULL, 
OB_Bus_NumDDL30D INT NULL, 
OB_Bus_NumDD31to60D INT NULL, 
OB_Bus_NumDD61to90D INT NULL, 
OB_Bus_NumDD91to180D INT NULL, 
OB_Bus_NumDD181to365D INT NULL, 
OB_Bus_NumDD366to730D INT NULL, 
OB_Bus_AmtNegSAVINGSL30D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegSAVINGSL60D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegSAVINGSL90D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegSAVINGSL180D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegSAVINGS DECIMAL(20, 2) NULL, 
OB_Bus_NumNegTransREVERSEDEBTSL30D INT NULL, 
OB_Bus_NumNegTransREVERSEDEBTSL60D INT NULL, 
OB_Bus_NumNegTransREVERSEDEBTSL90D INT NULL, 
OB_Bus_NumNegTransREVERSEDEBTSL180D INT NULL, 
OB_Bus_NumNegTransREVERSEDEBTS INT NULL, 
OB_Bus_NumNegTransCHARGESL30D INT NULL, 
OB_Bus_NumNegTransCHARGESL60D INT NULL, 
OB_Bus_NumNegTransCHARGESL90D INT NULL, 
OB_Bus_NumNegTransCHARGESL180D INT NULL, 
OB_Bus_NumNegTransCHARGES INT NULL, 
OB_Bus_NumNegTransFINESL30D INT NULL, 
OB_Bus_NumNegTransFINESL60D INT NULL, 
OB_Bus_NumNegTransFINESL90D INT NULL, 
OB_Bus_NumNegTransFINESL180D INT NULL, 
OB_Bus_NumNegTransFINES INT NULL, 
OB_Bus_NUMTRANSOVER5KL30D INT NULL, 
OB_Bus_NUMTRANSOVER5KL60D INT NULL, 
OB_Bus_NUMTRANSOVER5KL90D INT NULL, 
OB_Bus_NUMTRANSOVER5KL180D INT NULL, 
OB_Bus_NUMTRANSOVER5K INT NULL, 
OB_Bus_AmtNegLOANSL30D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegLOANSL60D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegLOANSL90D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegLOANSL180D DECIMAL(20, 2) NULL, 
OB_Bus_AmtNegLOANS DECIMAL(20, 2) NULL, 
);